# basic options
title: Douglas Herron
author: Douglas Herron
email: douglasherron16@gmail.com
description: Programming Student
twitter_username: N/A
github_username:  Douglas Herron

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
